USE [CafeOrderManagement]
GO

/****** Object:  Index [IX_MenuItems_CategoryId]    Script Date: 7.11.2024 00:56:13 ******/
CREATE NONCLUSTERED INDEX [IX_MenuItems_CategoryId] ON [dbo].[MenuItems]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

